version: "2"

services:
  pyspark:
    build: ./pyspark/.
    hostname: pyspark
    links:
      - mongodb:mongodb
    networks:
      - connector
  mongodb:
    build: ./mongodb/.
    image: mongodb
    expose:
      - 27017
    ports:
      - 27017:27017
    networks: 
      - connector

networks:
  connector:
